name: MorperX_Core
version: 1.2.0
main: me.morperx.core.MorperXCore
api-version: '1.21'

author: MorperX
description: MorperX Minecraft Server Core

commands:

  sunucu:
    description: Sunucu seçim menüsünü açar.
    usage: /sunucu

  mod:
    description: Oyun modu seçim menüsünü açar.
    usage: /mod
